create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  notification_id bigint not null references public.notificationpanel (id) on delete cascade,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, notification_id)
);

create index if not exists idx_user_notifications_user_id
  on public.user_notifications (user_id);

create index if not exists idx_user_notifications_notification_id
  on public.user_notifications (notification_id);
