import { createContext, useContext, useState } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'si', label: 'සිංහල', short: 'සිං' },
  { code: 'ta', label: 'தமிழ்', short: 'த' },
]

export const translations = {
  en: {
    // ── Nav ──
    dashboard: 'Dashboard',
    fieldData: 'Field Data',
    map: 'Map',
    weather: 'Weather',
    alerts: 'Alerts',
    report: 'Report',
    help: 'Help',
    searchPlaceholder: 'Search analytics...',
    noResults: 'No results for',

    // ── Dashboard ──
    welcomeTitle: 'Welcome to RiceVision',
    welcomeSubtitle: 'Insights of smarter farming',
    systemSynced: 'System Synchronized',
    cropHealthDist: 'Crop Health Distribution',
    analysing: 'Analysing...',
    optimal: 'Optimal',
    mildStress: 'Mild Stress',
    severeStress: 'Severe Stress',
    outputProjection: 'Output Projection',
    metricTons: 'Metric Tons (Est.)',
    highPerformance: 'High Performance Sectors',
    supplyStability: 'Supply Stability',
    expectedShortfall: 'Expected Shortfall (MT)',
    nationalDemand: 'National Demand Saturation',
    referenceThreshold: 'Reference: 3.0M MT Threshold',
    diseaseOutbreak: 'Disease & Disaster Outbreak',
    checkingFields: 'Checking Fields...',
    alertsDetected: 'Alerts Detected',
    viewDetails: 'View Details',
    showLess: 'Show Less',
    showAll: 'Show All',
    growthAnalysis: 'Growth Analysis',
    cropStageDistribution: 'Crop Stage Distribution',
    totalFieldsTracked: 'Total Fields Tracked',
    districtHealthMap: 'District Health Map',

    // ── Alerts ──
    fieldRiskAlerts: 'Field Risk Alerts',
    automatedMonitoring: 'Automated Sentinel Monitoring',
    active: 'Active',
    resolved: 'Resolved',
    disasters: 'Disasters',
    pestRisks: 'Pest Risks',
    pastAlerts: 'Past Alerts',
    findAnomaly: 'Find specific anomaly...',
    noThreats: 'No active threats detected',
    resolveBtn: 'Resolve',
    ignoreBtn: 'Ignore',
    viewInMap: 'View in Map',

    // ── Help ──
    helpSupport: 'Help & Support',
    quickAssistance: 'Quick Assistance',
    quickAssistanceDesc: 'Immediate tactical assistance for critical infrastructure failures.',
    dialConcierge: 'Dial Concierge',
    askTeam: 'Ask Our Team',
    askTeamDesc: 'Submit non-urgent data requests or detailed system feedback.',
    transmitEmail: 'Transmit Email',
    feedbackLoop: 'Intelligence Feedback Loop',
    fullOperatorName: 'Full Operator Name',
    assignedPosition: 'Assigned Position',
    province: 'Province',
    district: 'District',
    anomalyType: 'Anomaly Type',
    selectSeverity: 'Select Severity',
    detailedMessage: 'Detailed Diagnostic Message',
    describeIssue: 'Describe the issue in detail so we can help you....',
    transmitting: 'Transmitting...',
    submitReport: 'Submit Your Report',
    quickHelp: 'Quick Help',
    decryptingFaqs: 'Decrypting FAQs...',

    // ── Field Data ──
    fieldIntelligence: 'Field Intelligence',
    liveStream: 'Live Sentinel Stream',
    decryptingIntel: 'Decrypting Field Intelligence...',
    districtPerformance: 'District-wise Performance Summary',
    colDistrict: 'District',
    colTotalFields: 'Total Fields',
    colHealthy: 'Healthy',
    colStressed: 'Stressed',
    colCritical: 'Critical',
    colAvgYield: 'Avg Yield (kg/ha)',
    colTotalYield: 'Total Yield (kg)',

    // ── Weather ──
    weatherTitle: 'Weather Intelligence',
    locating: 'Locating...',
    locateMe: 'Locate Me',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    todayRain: 'Today Rain',
    feelsLike: 'Feels like',
    humidity: 'Humidity',
    cloudCover: 'Cloud Cover',
    atmospheric: 'Atmospheric Conditions',
    tabOverview: 'Overview',
    tabHourly: 'Hourly',
    tab14Day: '14-Day',
    tabSoil: 'Soil',
    tabAgriculture: 'Agriculture',

    // ── Report ──
    reportTitle: 'Yield Analytics',
    singleDistrict: 'Single District',
    compareDistricts: 'Compare Districts',
    generateReport: 'Generate Report',
    downloadPdf: 'Download PDF',
    season: 'Season',
    noData: 'No data available',
    loading: 'Loading...',

    // ── Profile ──
    operatorAuth: 'Operator Authorization',
    identityProfile: 'Identity Profile',
    profileDesc: 'Synthesize and finalize your operator credentials within the RiceVision network. All modifications are recorded permanently in the regional registry.',
    personalId: 'Personal Identification',
    sectorReg: 'Sector Registration',
    givenName: 'Given Name',
    surname: 'Surname',
    identification: 'Identification (NIC)',
    tacticalPhone: 'Tactical Phone',
    emailEndpoint: 'Encryption Endpoint (Email)',
    address: 'Operational Zone (Address)',
    uploadingMatrix: 'Uploading Matrix...',
    updating: 'Applying Changes...',
    updateProfile: 'Synchronize Identity',

    // ── Notifications ──
    notifications: 'Notifications',
    noNotifications: 'No notifications',

    // ── Sign In ──
    welcomeBack: 'Welcome Back',
    signInDetails: 'Please enter your details to access your dashboard.',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    keepLoggedIn: 'Keep me logged in',
    signingIn: 'Signing in...',
    signInBtn: 'Sign In to Account',
    orDivider: 'OR',
    noAccount: "Don't have an account?",
    signUpLink: 'Sign up',
    continueGoogle: 'Continue with Google',

    // ── Sign Up ──
    createAccount: 'Create Account',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    alreadyAccount: 'Already have an account?',
    signInLink: 'Sign in',
    signingUp: 'Creating account...',
    signUpBtn: 'Create Account',
  },

  si: {
    // ── Nav ──
    dashboard: 'උපකරණ පුවරුව',
    fieldData: 'කෙත් දත්ත',
    map: 'සản-ල',
    weather: 'කාලගුණය',
    alerts: 'අනතුරු ඇඟවීම්',
    report: 'වාර්තාව',
    help: 'උදව්',
    searchPlaceholder: 'සොයන්න...',
    noResults: 'ප්‍රතිඵල නොමැත',

    // ── Dashboard ──
    welcomeTitle: 'RiceVision වෙත සාදරයෙන් පිළිගනිමු',
    welcomeSubtitle: 'දක්ෂ ගොවිතැනෙහි අවබෝධය',
    systemSynced: 'පද්ධතිය සමමුහුර්ත කර ඇත',
    cropHealthDist: 'බෝග සෞඛ්‍ය බෙදාහැරීම',
    analysing: 'විශ්ලේෂණය කරමින්...',
    optimal: 'ශ්‍රේෂ්ඨ',
    mildStress: 'මෘදු ඒකාග්‍රතාව',
    severeStress: 'දැඩි ඒකාග්‍රතාව',
    outputProjection: 'නිෂ්පාදන අනාවැකිය',
    metricTons: 'මෙට්‍රික් ටොන් (ඇ.)',
    highPerformance: 'ඉහළ කාර්ය සාධන ප්‍රදේශ',
    supplyStability: 'සැපයුම් ස්ථාවරත්වය',
    expectedShortfall: 'අපේක්ෂිත හිඟය (MT)',
    nationalDemand: 'ජාතික ඉල්ලුම් සන්තෘප්තිය',
    referenceThreshold: 'ආශ්‍රිතය: MT 3.0M සීමාව',
    diseaseOutbreak: 'රෝග හා ව්‍යසන ආගමනය',
    checkingFields: 'කෙත් පරීක්ෂා කරමින්...',
    alertsDetected: 'ඇඟවීම් හඳුනාගෙන ඇත',
    viewDetails: 'විස්තර බලන්න',
    showLess: 'අඩු කරන්න',
    showAll: 'සියල්ල බලන්න',
    growthAnalysis: 'වර්ධන විශ්ලේෂණය',
    cropStageDistribution: 'බෝග අදියර බෙදාහැරීම',
    totalFieldsTracked: 'ලුහුඬු කළ කෙත් ගණන',
    districtHealthMap: 'දිස්ත්‍රික් සෞඛ්‍ය සản-ල',

    // ── Alerts ──
    fieldRiskAlerts: 'කෙත් අවදානම් ඇඟවීම්',
    automatedMonitoring: 'ස්වයංක්‍රීය නිරීක්ෂණය',
    active: 'ක්‍රියාකාරී',
    resolved: 'විසඳා ඇත',
    disasters: 'ව්‍යසන',
    pestRisks: 'පළිබෝධ අවදානම්',
    pastAlerts: 'පෙර ඇඟවීම්',
    findAnomaly: 'නිශ්චිත විෂමතාව සොයන්න...',
    noThreats: 'ක්‍රියාකාරී තර්ජන හඳුනාගෙන නැත',
    resolveBtn: 'විසඳන්න',
    ignoreBtn: 'නොසලකන්න',
    viewInMap: 'සản-ලෙ බලන්න',

    // ── Help ──
    helpSupport: 'උදව් සහ සහාය',
    quickAssistance: 'ඉක්මන් සහාය',
    quickAssistanceDesc: 'තීරණාත්මක යටිතල අකාමාවන් සඳහා ඉක්මන් සහාය.',
    dialConcierge: 'ඇමතුම ගන්න',
    askTeam: 'කණ්ඩායමෙන් අසන්න',
    askTeamDesc: 'හදිසි නොවන දත්ත ඉල්ලීම් හෝ ප්‍රතිපෝෂණ ඉදිරිපත් කරන්න.',
    transmitEmail: 'ඊමේල් යවන්න',
    feedbackLoop: 'ප්‍රතිපෝෂණ පරිපාලනය',
    fullOperatorName: 'සම්පූර්ණ නාමය',
    assignedPosition: 'නිශ්චිත තනතුර',
    province: 'පළාත',
    district: 'දිස්ත්‍රික්කය',
    anomalyType: 'ගැටලු වර්ගය',
    selectSeverity: 'බරපතල බව තෝරන්න',
    detailedMessage: 'සවිස්තරාත්මක පණිවිඩය',
    describeIssue: 'ගැටලුව සවිස්තරාත්මකව විස්තර කරන්න...',
    transmitting: 'යවමින්...',
    submitReport: 'වාර්තාව ඉදිරිපත් කරන්න',
    quickHelp: 'ඉක්මන් උදව්',
    decryptingFaqs: 'FAQs පූරණය කරමින්...',

    // ── Field Data ──
    fieldIntelligence: 'කෙත් බුද්ධිය',
    liveStream: 'සජීව ධාරාව',
    decryptingIntel: 'කෙත් දත්ත විශ්ලේෂණය කරමින්...',
    districtPerformance: 'දිස්ත්‍රික් කාර්ය සාධන සාරාංශය',
    colDistrict: 'දිස්ත්‍රික්කය',
    colTotalFields: 'මුළු කෙත්',
    colHealthy: 'සෞඛ්‍ය සම්පන්න',
    colStressed: 'ඒකාග්‍ර',
    colCritical: 'අනතුරු',
    colAvgYield: 'සාමාන්‍ය අස්වැන්න (kg/ha)',
    colTotalYield: 'මුළු අස්වැන්න (kg)',

    // ── Weather ──
    weatherTitle: 'කාලගුණ තොරතුරු',
    locating: 'ස්ථාන ලබා ගනිමින්...',
    locateMe: 'මාව සොයන්න',
    sunrise: 'සූර්යෝදය',
    sunset: 'සූර්යාස්තය',
    todayRain: 'අද වැස්ස',
    feelsLike: 'දැනෙන ශීතලය',
    humidity: 'ආර්ද්‍රතාව',
    cloudCover: 'වලා ආවරණය',
    atmospheric: 'වායුගෝලීය තත්ත්ව',
    tabOverview: 'දළ විශ්ලේෂණය',
    tabHourly: 'පැය-by-පැය',
    tab14Day: 'දින 14',
    tabSoil: 'පසෙ',
    tabAgriculture: 'කෘෂිකර්ම',

    // ── Report ──
    reportTitle: 'අස්වැන්න විශ්ලේෂණය',
    singleDistrict: 'තනි දිස්ත්‍රික්කය',
    compareDistricts: 'දිස්ත්‍රික් සංසන්දනය',
    generateReport: 'වාර්තාව ජනනය කරන්න',
    downloadPdf: 'PDF බාගන්න',
    season: 'කාලය',
    noData: 'දත්ත නොමැත',
    loading: 'පූරණය...',

    // ── Profile ──
    operatorAuth: 'ක්‍රියාකරු අනුමැතිය',
    identityProfile: 'අනන්‍යතා විස්තරය',
    profileDesc: 'RiceVision ජාලයේ ඔබේ ක්‍රියාකරු අක්‍රිය සාකාරය සාකච්ඡා කරන්න.',
    personalId: 'පෞද්ගලික හඳුනාගැනීම',
    sectorReg: 'ක්ෂේත්‍ර ලියාපදිංචිය',
    givenName: 'ලබා දුන් නාමය',
    surname: 'පවුලේ නාමය',
    identification: 'හැඳුනුම්පත (NIC)',
    tacticalPhone: 'දුරකථන අංකය',
    emailEndpoint: 'ඊමේල් ලිපිනය',
    address: 'ලිපිනය',
    uploadingMatrix: 'ඡායාරූපය යවමින්...',
    updating: 'යාවත්කාලීන කරමින්...',
    updateProfile: 'අනන්‍යතාව සමමුහුර්ත කරන්න',

    // ── Notifications ──
    notifications: 'දැනුම්දීම්',
    noNotifications: 'දැනුම්දීම් නොමැත',

    // ── Sign In ──
    welcomeBack: 'ආයුබෝවන්',
    signInDetails: 'ඔබේ ගිණුම ප්‍රවේශ වීමට විස්තර ඇතුළත් කරන්න.',
    emailAddress: 'ඊමේල් ලිපිනය',
    password: 'මුරපදය',
    forgotPassword: 'මුරපදය අමතකද?',
    keepLoggedIn: 'ලොගිනව තබා ගන්න',
    signingIn: 'ඇතුල් වෙමින්...',
    signInBtn: 'ගිණුමට ඇතුල් වන්න',
    orDivider: 'හෝ',
    noAccount: 'ගිණුමක් නැද්ද?',
    signUpLink: 'ලියාපදිංචි වන්න',
    continueGoogle: 'Google සමඟ දිගටම',

    // ── Sign Up ──
    createAccount: 'ගිණුමක් සාදන්න',
    fullName: 'සම්පූර්ණ නාමය',
    confirmPassword: 'මුරපදය තහවුරු කරන්න',
    alreadyAccount: 'දැනටමත් ගිණුමක් තිබේද?',
    signInLink: 'ඇතුල් වන්න',
    signingUp: 'ගිණුම සාදමින්...',
    signUpBtn: 'ගිණුමක් සාදන්න',
  },

  ta: {
    // ── Nav ──
    dashboard: 'டாஷ்போர்டு',
    fieldData: 'வயல் தரவு',
    map: 'வரைபடம்',
    weather: 'வானிலை',
    alerts: 'எச்சரிக்கைகள்',
    report: 'அறிக்கை',
    help: 'உதவி',
    searchPlaceholder: 'தேடுங்கள்...',
    noResults: 'முடிவுகள் இல்லை',

    // ── Dashboard ──
    welcomeTitle: 'RiceVision-க்கு வரவேற்கிறோம்',
    welcomeSubtitle: 'சிறந்த விவசாயத்தின் நுண்ணறிவு',
    systemSynced: 'கணினி இணைக்கப்பட்டது',
    cropHealthDist: 'பயிர் ஆரோக்கிய விநியோகம்',
    analysing: 'பகுப்பாய்வு செய்கிறது...',
    optimal: 'உகந்த',
    mildStress: 'மிதமான அழுத்தம்',
    severeStress: 'கடுமையான அழுத்தம்',
    outputProjection: 'உற்பத்தி முன்னிறுத்தல்',
    metricTons: 'மெட்ரிக் டன் (மதி.)',
    highPerformance: 'உயர் செயல்திறன் பகுதிகள்',
    supplyStability: 'வழங்கல் நிலைத்தன்மை',
    expectedShortfall: 'எதிர்பார்க்கப்படும் பற்றாக்குறை (MT)',
    nationalDemand: 'தேசிய தேவை திருப்திகரம்',
    referenceThreshold: 'குறிப்பு: 3.0M MT வரம்பு',
    diseaseOutbreak: 'நோய் & பேரழிவு வெடிப்பு',
    checkingFields: 'வயல்களை சரிபார்க்கிறது...',
    alertsDetected: 'எச்சரிக்கைகள் கண்டறியப்பட்டன',
    viewDetails: 'விவரங்கள் காண்க',
    showLess: 'குறைவாக காட்டு',
    showAll: 'அனைத்தும் காட்டு',
    growthAnalysis: 'வளர்ச்சி பகுப்பாய்வு',
    cropStageDistribution: 'பயிர் கட்ட விநியோகம்',
    totalFieldsTracked: 'கண்காணிக்கப்படும் மொத்த வயல்கள்',
    districtHealthMap: 'மாவட்ட ஆரோக்கிய வரைபடம்',

    // ── Alerts ──
    fieldRiskAlerts: 'வயல் அபாய எச்சரிக்கைகள்',
    automatedMonitoring: 'தானியங்கி கண்காணிப்பு',
    active: 'செயலில்',
    resolved: 'தீர்வு காணப்பட்டது',
    disasters: 'பேரழிவுகள்',
    pestRisks: 'பூச்சி அபாயங்கள்',
    pastAlerts: 'கடந்த எச்சரிக்கைகள்',
    findAnomaly: 'குறிப்பிட்ட வினோதத்தை தேடுங்கள்...',
    noThreats: 'செயலில் உள்ள அச்சுறுத்தல்கள் இல்லை',
    resolveBtn: 'தீர்க்கவும்',
    ignoreBtn: 'புறக்கணிக்க',
    viewInMap: 'வரைபடத்தில் காண்க',

    // ── Help ──
    helpSupport: 'உதவி & ஆதரவு',
    quickAssistance: 'விரைவு உதவி',
    quickAssistanceDesc: 'முக்கியமான தகராறுகளுக்கு உடனடி உதவி.',
    dialConcierge: 'அழைக்கவும்',
    askTeam: 'எங்கள் குழுவிடம் கேளுங்கள்',
    askTeamDesc: 'அவசர அல்லாத கோரிக்கைகள் அல்லது கருத்துக்களை சமர்ப்பிக்கவும்.',
    transmitEmail: 'மின்னஞ்சல் அனுப்பவும்',
    feedbackLoop: 'கருத்து வழிமுறை',
    fullOperatorName: 'முழு இயக்குநர் பெயர்',
    assignedPosition: 'நியமிக்கப்பட்ட பதவி',
    province: 'மாகாணம்',
    district: 'மாவட்டம்',
    anomalyType: 'பிரச்சனை வகை',
    selectSeverity: 'தீவிரத்தை தேர்ந்தெடுக்கவும்',
    detailedMessage: 'விரிவான செய்தி',
    describeIssue: 'பிரச்சனையை விரிவாக விவரிக்கவும்...',
    transmitting: 'அனுப்புகிறது...',
    submitReport: 'அறிக்கையை சமர்ப்பிக்கவும்',
    quickHelp: 'விரைவு உதவி',
    decryptingFaqs: 'FAQs ஏற்றுகிறது...',

    // ── Field Data ──
    fieldIntelligence: 'வயல் நுண்ணறிவு',
    liveStream: 'நேரடி ஒளிபரப்பு',
    decryptingIntel: 'வயல் தரவு பகுப்பாய்வு செய்கிறது...',
    districtPerformance: 'மாவட்ட செயல்திறன் சுருக்கம்',
    colDistrict: 'மாவட்டம்',
    colTotalFields: 'மொத்த வயல்கள்',
    colHealthy: 'ஆரோக்கியமான',
    colStressed: 'அழுத்தமான',
    colCritical: 'ஆபத்தான',
    colAvgYield: 'சராசரி மகசூல் (kg/ha)',
    colTotalYield: 'மொத்த மகசூல் (kg)',

    // ── Weather ──
    weatherTitle: 'வானிலை நுண்ணறிவு',
    locating: 'இடம் கண்டறிகிறது...',
    locateMe: 'என்னை கண்டுபிடி',
    sunrise: 'சூரிய உதயம்',
    sunset: 'சூரிய அஸ்தமனம்',
    todayRain: 'இன்று மழை',
    feelsLike: 'உணர்வு',
    humidity: 'ஈரப்பதம்',
    cloudCover: 'மேக மூட்டம்',
    atmospheric: 'வளிமண்டல நிலைமைகள்',
    tabOverview: 'கண்ணோட்டம்',
    tabHourly: 'மணிநேர',
    tab14Day: '14 நாட்கள்',
    tabSoil: 'மண்',
    tabAgriculture: 'விவசாயம்',

    // ── Report ──
    reportTitle: 'மகசூல் பகுப்பாய்வு',
    singleDistrict: 'ஒற்றை மாவட்டம்',
    compareDistricts: 'மாவட்டங்களை ஒப்பிடு',
    generateReport: 'அறிக்கை உருவாக்கு',
    downloadPdf: 'PDF பதிவிறக்கு',
    season: 'பருவம்',
    noData: 'தரவு இல்லை',
    loading: 'ஏற்றுகிறது...',

    // ── Profile ──
    operatorAuth: 'இயக்குநர் அங்கீகாரம்',
    identityProfile: 'அடையாள சுயவிவரம்',
    profileDesc: 'RiceVision நெட்வொர்க்கில் உங்கள் இயக்குநர் சான்றுகளை முடிக்கவும்.',
    personalId: 'தனிப்பட்ட அடையாளம்',
    sectorReg: 'துறை பதிவு',
    givenName: 'முதல் பெயர்',
    surname: 'குடும்ப பெயர்',
    identification: 'அடையாளம் (NIC)',
    tacticalPhone: 'தொலைபேசி',
    emailEndpoint: 'மின்னஞ்சல் முகவரி',
    address: 'முகவரி',
    uploadingMatrix: 'புகைப்படம் பதிவேற்றுகிறது...',
    updating: 'புதுப்பிக்கிறது...',
    updateProfile: 'அடையாளத்தை ஒத்திசைக்கவும்',

    // ── Notifications ──
    notifications: 'அறிவிப்புகள்',
    noNotifications: 'அறிவிப்புகள் இல்லை',

    // ── Sign In ──
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signInDetails: 'உங்கள் டாஷ்போர்டை அணுக விவரங்களை உள்ளிடவும்.',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    keepLoggedIn: 'உள்நுழைந்திருக்கவும்',
    signingIn: 'உள்நுழைகிறது...',
    signInBtn: 'கணக்கில் உள்நுழைக',
    orDivider: 'அல்லது',
    noAccount: 'கணக்கு இல்லையா?',
    signUpLink: 'பதிவு செய்யவும்',
    continueGoogle: 'Google மூலம் தொடரவும்',

    // ── Sign Up ──
    createAccount: 'கணக்கு உருவாக்கவும்',
    fullName: 'முழு பெயர்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    alreadyAccount: 'ஏற்கனவே கணக்கு இருக்கிறதா?',
    signInLink: 'உள்நுழையவும்',
    signingUp: 'கணக்கு உருவாக்குகிறது...',
    signUpBtn: 'கணக்கு உருவாக்கவும்',
  },
}

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'
  })

  const handleSetLanguage = (code) => {
    setLanguage(code)
    localStorage.setItem('language', code)
  }

  const t = (key) => translations[language]?.[key] ?? translations['en'][key] ?? key

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
