name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'ricevision-pipeline/**'
      - '.github/workflows/deploy-ricevision-ec2.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 60m
          command_timeout: 60m
          script: |
            set -e
            set -x

            cd /home/ec2-user/app/RiceVision || exit
            chmod +x deploy.sh
            ./deploy.sh